feat: 🎸 Added option to set the WUI registrar.hideProxy option
CESNET/ansible-role-perun-docker-server pull request #28
Opened 2022-05-11 06:31 UTC by dBucik

Use variable *perun_oldgui_registrar_hide_proxy* to set EntityIDs of
proxies that should be hidden on the similar user found.

2022-05-23 12:58 UTC, dBucik commented
@balcirakpeter ping :)

2022-07-08 13:04 UTC, martin-kuba requested changes

2022-07-08 13:04 UTC, martin-kuba commented on defaults/main.yml
> +perun_oldgui_registrar_hide_proxy: ''
The comment in perun-web-gui.properties.j2 says that the value should be a list, not a string.
```suggestion
perun_oldgui_registrar_hide_proxy: []
```

2022-07-08 13:04 UTC, martin-kuba commented on templates/perun-web-gui.properties.j2
> +registrar.hideProxy={{ perun_oldgui_registrar_hide_proxy }}
Converting a list into a comma-separated list can be done in this way:
```suggestion
registrar.hideProxy={{ perun_oldgui_registrar_hide_proxy|join(', ') }}
```

2022-07-11 10:41 UTC, martin-kuba approved these changes

2022-07-11 10:43 UTC, merged