Preparations for VSUP migration to Ansible
CESNET/ansible-role-perun-docker-server pull request #59
Opened 2023-02-08 15:41 UTC by xkostka2

2023-02-09 09:54 UTC, martin-kuba requested changes

2023-02-09 09:54 UTC, martin-kuba commented on defaults/main.yml
> +perun_apache_cors_headers_enabled: yes
the variable was removed, because it was always true
```suggestion
```

2023-02-09 09:54 UTC, martin-kuba commented on templates/perun.properties.j2
> +perun.registrar.principals = {{ perun_registrar_principals|join(', ') }}
keep the property as is

2023-02-09 09:54 UTC, martin-kuba commented on templates/sites-enabled/perun-api.conf.j2
> +{{ perun_apache_special_config3 }}
rename it to something that shows that it is used for API, like perun_apache_api_special_config
```suggestion
{{ perun_apache_api_special_config }}
```

2023-02-09 13:15 UTC, zlamalp requested changes

2023-02-09 13:15 UTC, zlamalp commented on templates/instance_configs/instanceConfig.json.j2
> +  "profile_label_en": "Profile",
`profile_label_en` is part of `defaultConfig.json` so I don't think we need to re-define it here unless custom value is expected.

2023-02-09 13:15 UTC, zlamalp commented on defaults/main.yml
> +perun_apache_default_registrar_rewrite_rules: ""
This should be revisited based on the feedback provided about the template for apache config.

2023-02-09 16:33 UTC, martin-kuba requested changes

2023-02-09 16:33 UTC, martin-kuba commented on templates/perun-engine.j2
> +{% if perun_engine_lwp_ssl_verify_hostname_flag is defined %}
It is not clear form the name of the variable what the values mean.
```suggestion
{% if perun_engine_verify_hostname_disabled is defined and perun_engine_verify_hostname_disabled %}
```

2023-02-09 17:51 UTC, zlamalp requested changes

2023-02-09 17:51 UTC, zlamalp commented on templates/sites-enabled/perun.conf.j2
> +  RewriteRule ^[/]?$ https://%{HTTP_HOST}/{{ perun_apache_gui_default_auth }}/gui/ [L]
You should do the same on line 170 (generic redirect for the GUI) as this line apply only to case when GUI is a default app on the domain.

2023-02-09 17:51 UTC, zlamalp commented on defaults/main.yml
> +perun_apache_gui_default_auth: "fed"
Probably move it closer to the line 510, where a similar config for registrar is placed. Also probably update the comment on 456 where /fed/gui/ should mention configurable prefix like the comment on 459.

2023-02-10 12:23 UTC, zlamalp approved these changes

2023-02-10 13:21 UTC, martin-kuba approved these changes

2023-02-10 13:22 UTC, merged